import React, { useState } from 'react';
import { 
  FolderTree, 
  FileCode, 
  Download, 
  Copy, 
  Check, 
  Save, 
  Plus, 
  Trash2, 
  FileText, 
  Terminal, 
  Package, 
  Sparkles,
  ExternalLink,
  Search,
  Code2,
  ChevronLeft,
  ListFilter
} from 'lucide-react';
import { PluginProject, PluginFile } from '../types';

interface PluginWorkspaceProps {
  project?: PluginProject;
  onUpdateFile: (path: string, newContent: string) => void;
  onAddFile: (file: PluginFile) => void;
  onDeleteFile: (path: string) => void;
  onDownloadJar: () => void;
  onDownloadZip: () => void;
  onAskRexaToFix: (fileSnippet: string) => void;
}

export const PluginWorkspace: React.FC<PluginWorkspaceProps> = ({
  project,
  onUpdateFile,
  onAddFile,
  onDeleteFile,
  onDownloadJar,
  onDownloadZip,
  onAskRexaToFix,
}) => {
  const [selectedFilePath, setSelectedFilePath] = useState<string>(() => {
    return project?.files[0]?.path || 'src/main/resources/plugin.yml';
  });
  const [mobileView, setMobileView] = useState<'files' | 'code'>('code');
  const [copied, setCopied] = useState(false);
  const [isEditing, setIsEditing] = useState(false);
  const [editContent, setEditContent] = useState('');
  const [newFileName, setNewFileName] = useState('');
  const [showAddModal, setShowAddModal] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const activeFile = project?.files.find(f => f.path === selectedFilePath) || project?.files[0];

  const handleSelectFile = (path: string) => {
    setSelectedFilePath(path);
    setIsEditing(false);
    setMobileView('code'); // On mobile, automatically show the selected code
  };

  const startEdit = () => {
    if (activeFile) {
      setEditContent(activeFile.content);
      setIsEditing(true);
    }
  };

  const saveEdit = () => {
    if (activeFile) {
      onUpdateFile(activeFile.path, editContent);
      setIsEditing(false);
    }
  };

  const handleCopy = () => {
    if (activeFile) {
      navigator.clipboard.writeText(activeFile.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleCreateFile = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newFileName.trim()) return;

    let path = newFileName.trim();
    if (!path.includes('/')) {
      path = `src/main/java/${path}`;
    }

    let language: 'java' | 'yaml' | 'xml' | 'markdown' = 'java';
    if (path.endsWith('.yml') || path.endsWith('.yaml')) language = 'yaml';
    else if (path.endsWith('.xml')) language = 'xml';
    else if (path.endsWith('.md')) language = 'markdown';

    const newFile: PluginFile = {
      path,
      content: language === 'java' 
        ? `package com.rexa.plugin;\n\npublic class ${path.split('/').pop()?.replace('.java', '')} {\n    // Code generated by Rexa AI\n}\n`
        : '# Created with Rexa AI\n',
      language,
    };

    onAddFile(newFile);
    setSelectedFilePath(newFile.path);
    setNewFileName('');
    setShowAddModal(false);
  };

  if (!project || project.files.length === 0) {
    return (
      <div className="flex-1 flex flex-col items-center justify-center p-8 text-center bg-gradient-to-b from-[#070210] to-black min-h-[calc(100vh-4rem)]">
        <div className="w-16 h-16 rounded-2xl bg-purple-950/40 border border-purple-500/30 flex items-center justify-center mb-4 shadow-purple-glow">
          <Code2 className="w-8 h-8 text-purple-400" />
        </div>
        <h2 className="text-xl font-bold text-white mb-2">No Active Plugin Project</h2>
        <p className="text-sm text-slate-400 max-w-md mb-6 leading-relaxed">
          Ask Rexa AI in the studio to create any Minecraft plugin (e.g. Paper 26.2 Custom Enchants, Folia RTP, or Vault Economy), and the complete source code tree will appear here.
        </p>
      </div>
    );
  }

  const filteredFiles = project.files.filter(f => 
    f.path.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="flex-1 flex flex-col h-[calc(100dvh-4rem)] bg-[#070210] overflow-hidden">
      {/* Workspace Top Toolbar */}
      <div className="h-14 px-3 sm:px-6 border-b border-purple-500/20 bg-[#0d041c]/90 flex items-center justify-between gap-2 sm:gap-4 shrink-0">
        <div className="flex items-center gap-2 sm:gap-3 min-w-0">
          <div className="p-1.5 rounded-lg bg-purple-900/40 border border-purple-500/30 text-purple-300 shrink-0">
            <FolderTree className="w-4 h-4" />
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-1.5 sm:gap-2">
              <span className="font-bold text-xs sm:text-sm text-white truncate">
                {project.name}
              </span>
              <span className="text-[10px] px-1.5 sm:px-2 py-0.5 rounded bg-purple-950/80 border border-purple-500/30 text-purple-300 font-mono shrink-0">
                {project.platform.toUpperCase()}
              </span>
            </div>
            <span className="text-[10px] sm:text-[11px] text-slate-400 truncate block font-mono hidden xs:block">
              Main: {project.mainClass.split('.').pop()}
            </span>
          </div>
        </div>

        {/* Mobile View Toggle Switcher (Files vs Code) */}
        <div className="flex md:hidden items-center p-0.5 rounded-lg bg-black/60 border border-purple-500/20 shrink-0">
          <button
            onClick={() => setMobileView('files')}
            className={`px-2.5 py-1 rounded-md text-xs font-semibold transition-all ${
              mobileView === 'files'
                ? 'bg-purple-600 text-white shadow-purple-glow'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Files ({filteredFiles.length})
          </button>
          <button
            onClick={() => setMobileView('code')}
            className={`px-2.5 py-1 rounded-md text-xs font-semibold transition-all ${
              mobileView === 'code'
                ? 'bg-purple-600 text-white shadow-purple-glow'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            Code
          </button>
        </div>

        {/* Toolbar action buttons */}
        <div className="flex items-center gap-1.5 sm:gap-2 shrink-0">
          <button
            onClick={onDownloadJar}
            className="flex items-center gap-1 px-2.5 sm:px-3 py-1.5 rounded-xl bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold shadow-purple-glow transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Download</span>
            <span>.JAR</span>
          </button>

          <button
            onClick={onDownloadZip}
            className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-[#17082e] hover:bg-purple-900/40 text-purple-200 border border-purple-500/30 text-xs font-medium transition-colors cursor-pointer"
          >
            <Package className="w-3.5 h-3.5 text-purple-400" />
            <span>.ZIP</span>
          </button>
        </div>
      </div>

      {/* Main Workspace Layout (Sidebar Tree + Code Editor) */}
      <div className="flex-1 flex overflow-hidden">
        {/* Left: File Tree Explorer */}
        <div className={`w-full md:w-64 lg:w-72 border-r border-purple-500/20 bg-[#090314]/90 flex flex-col shrink-0 ${
          mobileView === 'files' ? 'flex' : 'hidden md:flex'
        }`}>
          <div className="p-3 border-b border-purple-500/15 flex items-center justify-between gap-2">
            <div className="relative flex-1">
              <Search className="w-3.5 h-3.5 text-slate-500 absolute left-2.5 top-2.5" />
              <input
                type="text"
                placeholder="Search files..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-8 pr-2 py-1.5 rounded-lg bg-black/40 border border-purple-500/20 text-xs text-slate-200 placeholder-slate-500 focus:outline-none focus:border-purple-500"
              />
            </div>

            <button
              onClick={() => setShowAddModal(true)}
              className="p-1.5 rounded-lg bg-purple-900/30 hover:bg-purple-900/60 text-purple-300 border border-purple-500/30 transition-colors"
              title="Add New File"
            >
              <Plus className="w-4 h-4" />
            </button>
          </div>

          {/* Files List */}
          <div className="flex-1 overflow-y-auto p-2 space-y-1">
            <div className="px-2 py-1 text-[10px] font-bold uppercase text-purple-400/80 tracking-wider">
              Project Files ({filteredFiles.length})
            </div>

            {filteredFiles.map((file) => {
              const isSelected = file.path === activeFile?.path;
              const fileName = file.path.split('/').pop() || file.path;
              const isJava = file.path.endsWith('.java');
              const isYaml = file.path.endsWith('.yml') || file.path.endsWith('.yaml');
              const isXml = file.path.endsWith('.xml');

              return (
                <button
                  key={file.path}
                  onClick={() => handleSelectFile(file.path)}
                  className={`w-full flex items-center justify-between px-2.5 py-2.5 sm:py-2 rounded-lg text-left text-xs transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-purple-600/90 text-white font-medium shadow-purple-glow'
                      : 'text-slate-300 hover:text-white hover:bg-purple-950/40'
                  }`}
                >
                  <div className="flex items-center gap-2 min-w-0">
                    <span className={`text-[10px] font-mono px-1 py-0.2 rounded shrink-0 ${
                      isJava ? 'bg-amber-950/80 text-amber-300 border border-amber-500/30' :
                      isYaml ? 'bg-indigo-950/80 text-indigo-300 border border-indigo-500/30' :
                      isXml ? 'bg-sky-950/80 text-sky-300 border border-sky-500/30' :
                      'bg-slate-800 text-slate-300'
                    }`}>
                      {file.language.toUpperCase()}
                    </span>
                    <span className="truncate font-mono text-xs" title={file.path}>
                      {fileName}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Project Details Footer */}
          <div className="p-3 border-t border-purple-500/15 bg-black/40 text-[11px] text-slate-400 space-y-1">
            <div className="flex justify-between">
              <span>Platform:</span>
              <span className="text-purple-300 font-mono">{project.platform}</span>
            </div>
            <div className="flex justify-between">
              <span>Version:</span>
              <span className="text-purple-300 font-mono">{project.version}</span>
            </div>
            <div className="flex justify-between">
              <span>Java Runtime:</span>
              <span className="text-purple-300 font-mono">Java {project.javaVersion}</span>
            </div>
          </div>
        </div>

        {/* Right: Code Viewer & Editor */}
        <div className={`flex-1 flex-col bg-[#05010a] overflow-hidden ${
          mobileView === 'code' ? 'flex' : 'hidden md:flex'
        }`}>
          {activeFile ? (
            <>
              {/* File Header Bar */}
              <div className="h-11 px-3 sm:px-4 border-b border-purple-500/15 bg-[#0a0316] flex items-center justify-between gap-2 shrink-0">
                <div className="flex items-center gap-1.5 sm:gap-2 text-xs font-mono text-slate-300 truncate min-w-0">
                  {/* Back to Files button on mobile */}
                  <button
                    onClick={() => setMobileView('files')}
                    className="md:hidden flex items-center gap-1 text-purple-300 text-xs font-semibold px-2 py-1 rounded bg-purple-950/60 border border-purple-500/30 shrink-0"
                    title="Back to file list"
                  >
                    <ChevronLeft className="w-3.5 h-3.5" />
                    <span>Files</span>
                  </button>

                  <FileCode className="w-3.5 h-3.5 text-purple-400 shrink-0 hidden xs:block" />
                  <span className="text-purple-300 font-semibold truncate">{activeFile.path.split('/').pop()}</span>
                  <span className="text-slate-500 text-[11px] hidden sm:inline truncate">
                    ({activeFile.path})
                  </span>
                </div>

                <div className="flex items-center gap-1 sm:gap-2 shrink-0">
                  <button
                    onClick={handleCopy}
                    className="flex items-center gap-1 px-2 py-1 rounded bg-[#15072b] hover:bg-purple-900/40 text-purple-300 text-xs transition-colors cursor-pointer"
                    title="Copy File Code"
                  >
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    <span className="hidden xs:inline">{copied ? 'Copied' : 'Copy'}</span>
                  </button>

                  {isEditing ? (
                    <button
                      onClick={saveEdit}
                      className="flex items-center gap-1 px-2.5 py-1 rounded bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold transition-colors cursor-pointer"
                    >
                      <Save className="w-3.5 h-3.5" />
                      <span>Save</span>
                    </button>
                  ) : (
                    <button
                      onClick={startEdit}
                      className="flex items-center gap-1 px-2.5 py-1 rounded bg-purple-900/40 hover:bg-purple-900/70 border border-purple-500/30 text-purple-300 text-xs transition-colors cursor-pointer"
                    >
                      <span>Edit</span>
                    </button>
                  )}

                  <button
                    onClick={() => onAskRexaToFix(`File: ${activeFile.path}\n\`\`\`\n${activeFile.content}\n\`\`\``)}
                    className="flex items-center gap-1 px-2.5 py-1 rounded bg-gradient-to-r from-purple-600 to-indigo-600 text-white text-xs font-semibold shadow-purple-glow hover:scale-102 transition-all cursor-pointer"
                    title="Ask Rexa AI to inspect and optimize this file"
                  >
                    <Sparkles className="w-3 h-3" />
                    <span className="hidden sm:inline">Optimize with Rexa</span>
                    <span className="sm:hidden">Optimize</span>
                  </button>
                </div>
              </div>

              {/* Code Content Area */}
              <div className="flex-1 overflow-auto p-3 sm:p-4 font-mono text-xs leading-relaxed">
                {isEditing ? (
                  <textarea
                    value={editContent}
                    onChange={(e) => setEditContent(e.target.value)}
                    className="w-full h-full bg-black/60 text-slate-100 p-3 rounded-xl border border-purple-500/30 font-mono text-xs focus:outline-none resize-none leading-relaxed"
                  />
                ) : (
                  <div className="relative">
                    <pre className="text-slate-200 overflow-x-auto">
                      <code>
                        {activeFile.content.split('\n').map((line, idx) => (
                          <div key={idx} className="table-row hover:bg-purple-950/20">
                            <span className="table-cell pr-3 sm:pr-4 text-right select-none text-slate-600 text-[11px]">
                              {idx + 1}
                            </span>
                            <span className="table-cell whitespace-pre">
                              {line}
                            </span>
                          </div>
                        ))}
                      </code>
                    </pre>
                  </div>
                )}
              </div>
            </>
          ) : (
            <div className="flex-1 flex items-center justify-center text-slate-500 text-sm p-4 text-center">
              Select a file to inspect code
            </div>
          )}
        </div>
      </div>

      {/* Add File Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm">
          <div className="w-full max-w-md bg-[#0f051e] border border-purple-500/30 rounded-2xl p-6 shadow-purple-intense">
            <h3 className="text-base font-bold text-white mb-2">Add New Plugin File</h3>
            <p className="text-xs text-slate-400 mb-4">
              Enter relative file path (e.g. <code>src/main/java/com/rexa/listener/CustomListener.java</code> or <code>messages.yml</code>).
            </p>
            <form onSubmit={handleCreateFile} className="space-y-4">
              <input
                type="text"
                value={newFileName}
                onChange={(e) => setNewFileName(e.target.value)}
                placeholder="src/main/java/com/rexa/plugin/MyCommand.java"
                className="w-full px-3 py-2 rounded-xl bg-black/50 border border-purple-500/30 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-purple-500"
                autoFocus
              />
              <div className="flex justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setShowAddModal(false)}
                  className="px-3 py-1.5 rounded-lg text-xs text-slate-400 hover:text-white"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-1.5 rounded-lg bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold shadow-purple-glow"
                >
                  Create File
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
