import JSZip from 'jszip';
import { PluginProject } from '../types';

/**
 * Creates and triggers download of a Minecraft plugin .jar file
 */
export async function downloadPluginJar(project: PluginProject): Promise<void> {
  const zip = new JSZip();

  // 1. Add META-INF/MANIFEST.MF
  const manifestContent = [
    'Manifest-Version: 1.0',
    `Created-By: Rexa AI Plugin Architect (Minecraft ${project.minecraftVersion})`,
    `Implementation-Title: ${project.name}`,
    `Implementation-Version: ${project.version}`,
    `Main-Class: ${project.mainClass}`,
    `Built-By: Rexa AI`,
    `Build-Jdk: Java ${project.javaVersion}`,
    ''
  ].join('\r\n');

  zip.file('META-INF/MANIFEST.MF', manifestContent);

  // 2. Put plugin.yml and config.yml at the JAR root (where Bukkit/Paper classloader expects them)
  const pluginYmlFile = project.files.find(f => f.path.endsWith('plugin.yml') || f.path.endsWith('paper-plugin.yml'));
  if (pluginYmlFile) {
    const filename = pluginYmlFile.path.split('/').pop() || 'plugin.yml';
    zip.file(filename, pluginYmlFile.content);
  }

  const configYmlFile = project.files.find(f => f.path.endsWith('config.yml'));
  if (configYmlFile) {
    zip.file('config.yml', configYmlFile.content);
  }

  // 3. Add all project files into their paths
  for (const file of project.files) {
    zip.file(file.path, file.content);
  }

  // 4. Generate JAR blob
  const content = await zip.generateAsync({
    type: 'blob',
    mimeType: 'application/java-archive',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  // 5. Trigger download
  const cleanName = project.name.replace(/[^a-zA-Z0-9_-]/g, '');
  const fileName = `${cleanName}-${project.version || '1.0.0'}.jar`;
  saveBlob(content, fileName);
}

/**
 * Creates and triggers download of the full project source .zip file (Maven structure)
 */
export async function downloadPluginZip(project: PluginProject): Promise<void> {
  const zip = new JSZip();
  const rootFolderName = `${project.name.replace(/[^a-zA-Z0-9_-]/g, '')}-v${project.version}`;
  const folder = zip.folder(rootFolderName) || zip;

  for (const file of project.files) {
    folder.file(file.path, file.content);
  }

  // Include a quickstart build script
  folder.file('build.sh', `#!/usr/bin/env bash\n# Generated by Rexa AI for Minecraft ${project.minecraftVersion}\necho "Compiling ${project.name} with Maven..."\nmvn clean package\necho "Done! Your plugin JAR is located in target/${project.name}-${project.version}.jar"\n`);
  folder.file('build.bat', `@echo off\nREM Generated by Rexa AI for Minecraft ${project.minecraftVersion}\necho Compiling ${project.name} with Maven...\ncall mvn clean package\necho Done! Your plugin JAR is in target\\${project.name}-${project.version}.jar\npause\n`);

  const content = await zip.generateAsync({
    type: 'blob',
    mimeType: 'application/zip',
    compression: 'DEFLATE',
    compressionOptions: { level: 9 }
  });

  const cleanName = project.name.replace(/[^a-zA-Z0-9_-]/g, '');
  const fileName = `${cleanName}-${project.version || '1.0.0'}-Source.zip`;
  saveBlob(content, fileName);
}

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  setTimeout(() => {
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, 100);
}
